"""Reviewable baseline for the transitional click_gate facade surface."""

from __future__ import annotations


MAX_PRIVATE_FORWARDERS = 144

DOCUMENTED_LEGACY_FORWARDERS: dict[str, str] = {
    "_validate_contract": "click_contract.validate_contract",
}

HOST_ADAPTER_SURFACE: dict[str, frozenset[str]] = {
    "hooks/antigravity_gate.py": frozenset(
        {
            "SHELL_CONTROL_PUNCTUATION",
            "_emit",
            "_handle_post_tool",
            "_handle_pre_tool",
            "_handle_prompt_submit",
            "_handle_session_end",
            "_is_read_only_bash",
            "_set_output_adapter",
        }
    ),
    "hooks/click_hook.py": frozenset({"main"}),
}

PRIVATE_FORWARDERS: dict[str, str] = {
    "_active_prompt_turn_error": "click_lifecycle.active_prompt_turn_error",
    "_approved_contract_is_active": "click_lifecycle.approved_contract_is_active",
    "_arguments_have_filter": "click_verification._arguments_have_filter",
    "_browser_attempt_digest": "click_browser.attempt_digest",
    "_browser_evidence_required": "click_evidence.browser_required",
    "_browser_evidence_source_id": "click_evidence.browser_source_id",
    "_browser_input_error": "click_browser.input_error",
    "_browser_running_entry_is_active": "click_browser.running_entry_is_active",
    "_browser_running_expires_at": "click_browser.running_expires_at",
    "_build_read_only_git_argv": "click_inspection.build_read_only_git_argv",
    "_capability_digest": "click_capability.digest",
    "_claim_service_runner": "click_service.claim_service_runner",
    "_clear_contract_state": "click_lifecycle.clear_contract_state",
    "_clear_dependency_receipt": "click_verification.clear_dependency_receipt",
    "_clear_review_state": "click_observation.clear_review_state",
    "_command_parts": "click_capability.command_parts",
    "_consume_user_authorization": "click_lifecycle.consume_user_authorization",
    "_contains_deep_verification_marker": "click_verification._contains_deep_verification_marker",
    "_contract_id_from_state": "click_lifecycle.contract_id_from_state",
    "_contract_is_completed": "click_lifecycle.contract_is_completed",
    "_control_request": "click_lifecycle.control_request",
    "_copy_limited_output": "click_process.copy_limited_output",
    "_decode_capability_request": "click_capability.decode_request",
    "_decode_encoded_request": "click_capability.decode_encoded_request",
    "_dependency_declarations": "click_verification.dependency_declarations",
    "_dependency_receipt_is_valid": "click_verification.dependency_receipt_is_valid",
    "_dependency_receipt_matches": "click_verification.dependency_receipt_matches",
    "_direct_command_tokens": "click_inspection.direct_command_tokens",
    "_encoded_request": "click_capability.encode_request",
    "_ensure_evidence_state": "click_lifecycle.ensure_evidence_state",
    "_evidence_is_current": "click_evidence.is_current",
    "_evidence_key": "click_evidence.evidence_key",
    "_evidence_keys_for_kind": "click_evidence.keys_for_kind",
    "_evidence_registry_digest": "click_evidence.registry_digest",
    "_evidence_sources": "click_lifecycle.evidence_sources",
    "_executable_search_path": "click_verification._executable_search_path",
    "_execute_argv_commands": "click_inspection.execute_argv_commands",
    "_execute_inspection_commands": "click_inspection.execute_commands",
    "_execute_native_get_content": "click_inspection.execute_native_get_content",
    "_execute_read_only_git": "click_inspection.execute_read_only_git",
    "_execution_argv": "click_inspection.execution_argv",
    "_file_content_digest": "click_verification.file_content_digest",
    "_fresh_evidence_state": "click_evidence.fresh_state",
    "_fresh_external_evidence_state": "click_evidence.fresh_external_state",
    "_fresh_mutation_boundary": "click_mutation.fresh_boundary",
    "_fresh_mutation_state": "click_mutation.fresh_state",
    "_fresh_observation_state": "click_observation.fresh_state",
    "_fresh_service_state": "click_service.fresh_state",
    "_fresh_verification_state": "click_verification.fresh_state",
    "_get_content_paths": "click_inspection.get_content_paths",
    "_git_capture": "click_verification.git_capture",
    "_git_metadata_present": "click_inspection.git_metadata_present",
    "_git_option_allowed": "click_inspection.git_option_allowed",
    "_git_subcommand": "click_inspection.git_subcommand",
    "_git_workspace_snapshot": "click_verification.git_workspace_snapshot",
    "_hash_workspace_path": "click_verification.hash_workspace_path",
    "_inspection_request_from_bash": "click_inspection.request_from_bash",
    "_is_broad_exploration_tokens": "click_inspection.is_broad_exploration_tokens",
    "_is_git_remote_output_request": "click_inspection.is_git_remote_output_request",
    "_is_local_read_only_tokens": "click_inspection.is_local_read_only_tokens",
    "_is_path_qualified_executable": "click_inspection.is_path_qualified_executable",
    "_is_read_only_bash": "click_inspection.is_read_only_bash",
    "_is_read_only_git_remote_arguments": "click_inspection.is_read_only_git_remote_arguments",
    "_is_read_only_sed": "click_inspection.is_read_only_sed",
    "_is_read_only_tokens": "click_inspection.is_read_only_tokens",
    "_is_recognized_verification_command": "click_verification.is_recognized_command",
    "_is_recognized_verification_tokens": "click_verification.is_recognized_tokens",
    "_isolated_subprocess_kwargs": "click_process.isolated_subprocess_kwargs",
    "_looks_like_managed_service": "click_service.looks_like_managed_service",
    "_managed_observation_path": "click_observation.managed_path",
    "_minimum_test_runner_class": "click_verification._minimum_test_runner_class",
    "_minimum_verification_class": "click_verification.minimum_class",
    "_mutation_is_running": "click_mutation.is_running",
    "_new_untracked_is_suspicious": "click_verification.new_untracked_is_suspicious",
    "_observation_is_running": "click_observation.is_running",
    "_parse_read_only_git_tokens": "click_inspection.parse_read_only_git_tokens",
    "_path_is_within": "click_inspection.path_is_within",
    "_policy_executable_name": "click_capability.policy_executable_name",
    "_positional_arguments": "click_capability.positional_arguments",
    "_promote_dependency_receipt": "click_verification.promote_dependency_receipt",
    "_prompt_authorization": "click_lifecycle.prompt_authorization",
    "_prune_state": "click_lifecycle.prune_state",
    "_read_contract_state": "click_lifecycle.read_contract_state",
    "_read_default_mode": "click_lifecycle.read_default_mode",
    "_read_mode": "click_lifecycle.read_mode",
    "_read_review_state": "click_observation.read_review_state",
    "_read_state": "click_lifecycle.read_state",
    "_read_user_prompt_state": "click_lifecycle.read_user_prompt_state",
    "_read_user_prompt_turn": "click_lifecycle.read_user_prompt_turn",
    "_record_mutation_result": "click_mutation.record_result",
    "_record_observation_result": "click_observation.record_result",
    "_record_service_fields": "click_service.record_service_fields",
    "_record_user_prompt": "click_lifecycle.record_user_prompt",
    "_redact_git_remote_output": "click_inspection.redact_git_remote_output",
    "_redact_git_remote_url": "click_inspection.redact_git_remote_url",
    "_request_service_stop": "click_service.request_stop",
    "_resolve_read_only_executable": "click_inspection.resolve_read_only_executable",
    "_sanitized_executable_path": "click_inspection.sanitized_executable_path",
    "_sanitized_git_environment": "click_inspection.sanitized_git_environment",
    "_sanitized_read_only_environment": "click_inspection.sanitized_read_only_environment",
    "_save_contract_state": "click_lifecycle.save_contract_state",
    "_save_review_state": "click_observation.save_review_state",
    "_scope_with_kind_floor": "click_verification._scope_with_kind_floor",
    "_service_snapshot": "click_service.service_snapshot",
    "_session_contract_is_active": "click_lifecycle.session_contract_is_active",
    "_shell_segments": "click_capability.shell_segments",
    "_store_dependency_receipt": "click_verification.store_dependency_receipt",
    "_structured_ssh_parts": "click_inspection.structured_ssh_parts",
    "_targets_repository_root": "click_inspection.targets_repository_root",
    "_terminate_managed_child": "click_process.terminate_process_group",
    "_tool_response_failed": "click_browser.response_failed",
    "_unclaimed_reservation_is_fresh": "click_observation.unclaimed_reservation_is_fresh",
    "_unsafe_inherited_environment_key": "click_inspection.unsafe_inherited_environment_key",
    "_valid_git_worktree_marker": "click_inspection.valid_git_worktree_marker",
    "_validate_argv": "click_capability.validate_argv",
    "_validate_contract": "click_contract.validate_contract",
    "_validate_evidence_result": "click_lifecycle.validate_evidence_result",
    "_validate_inspection_request": "click_inspection.validate_request",
    "_validate_verification_batch": "click_verification.validate_batch",
    "_verification_environment": "click_verification.environment",
    "_verification_environment_binding": "click_verification.environment_binding",
    "_verification_environment_binding_digest": "click_verification.environment_binding_digest",
    "_verification_environment_binding_is_authentic": "click_verification.environment_binding_is_authentic",
    "_verification_environment_digest": "click_verification.environment_digest",
    "_verification_environment_digest_from_records": "click_verification.environment_digest_from_records",
    "_verification_environment_from_binding": "click_verification.environment_from_binding",
    "_verification_environment_hmac": "click_verification._verification_environment_hmac",
    "_verification_environment_key": "click_verification.environment_key",
    "_verification_executable_payload": "click_verification.executable_payload",
    "_verification_executable_records": "click_verification.executable_records",
    "_verification_group_digest": "click_verification.group_digest",
    "_verification_group_units": "click_verification.group_units",
    "_verification_groups": "click_verification.verification_groups",
    "_verification_host_coverage_binding_digest": "click_verification.host_coverage_binding_digest",
    "_verification_host_coverage_binding_is_authentic": "click_verification.host_coverage_binding_is_authentic",
    "_verification_receipt_matches": "click_verification.receipt_matches",
    "_verification_targets": "click_verification._verification_targets",
    "_workspace_boundary": "click_inspection.workspace_boundary",
    "_write_contract_state": "click_lifecycle.write_contract_state",
    "_write_default_mode": "click_lifecycle.write_default_mode",
    "_write_mode": "click_lifecycle.write_mode",
    "_write_review_state": "click_observation.write_review_state",
    "_write_runner_stream": "click_inspection.write_runner_stream",
    "_write_state": "click_lifecycle.write_state",
}
